# Site settings
author: Rachel Grier
title: Rachel Grier
header-img: img/home-bg.png
email: rgrier104@gmail.com
copyright_name: Rachel Grier
description: > # this means to ignore newlines until "baseurl:"
  My journey coding on an island in the middle of nowhere
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rgrier104

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
